# Generated by Django 4.2.3 on 2023-07-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistAPI', '0002_rename_work_artist_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='artists', to='ArtistAPI.work'),
        ),
    ]
